// /* eslint-disable */
// /**
//  * This file was automatically generated by json-schema-to-typescript.
//  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
//  * and run json-schema-to-typescript to regenerate this file.
//  */

// export interface IConstants {
//   readonly $schema?: string;
//   readonly database: {
//     readonly paginatedTables: {
//       /**
//        * This interface was referenced by `undefined`'s JSON-Schema definition
//        * via the `patternProperty` ".*".
//        */
//       [k: string]: string;
//     };
//     readonly sortingDirections: {
//       readonly ascending: SortingDirection;
//       readonly descending: SortingDirection;
//     };
//   };
// }
// export interface SortingDirection {
//   readonly aliases: readonly string[];
//   readonly sqlStatement: string;
// }